services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: react-flask
    ports:
      - 127.0.0.1:5000:5000
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-front
    ports:
      - 127.0.0.1:3000:3000
